In [2]:
import psycopg2

con = psycopg2.connect(
  database="db_dsa", 
  user="udsa", 
  password="P@ssword2021", 
  host="92.242.58.173", 
  port="1984"
)

print("Database opened successfully")

Database opened successfully


/opt/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [3]:
import pandas as pd
cur = con.cursor()
cur.execute("SELECT * from PROJECTS")
rows = cur.fetchall()
column_names=["ID","NUMBER","VACANCIES","NAME","TYPE","TYPEDESC","TYPEID","STATUSID", "STATUSDESC","DIRECTIONHEAD","HEAD","DATACREATED","FACULTYID"]
df = pd.DataFrame(rows, columns=column_names)

In [11]:
df1 = df[['NAME']]
df2 = df1.apply(lambda x: ';'.join(x.astype(str)), axis=1)
df_clean = pd.DataFrame({'clean': df2})
sent = [row.split(';') for row in df_clean['clean']]
sentences = []
for i in sent:
    sentences.append(i[0])

In [7]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [13]:
values = array(sentences)
print(values)

['Численное и аналитическое исследование эффекта Саффмана-Тейлора'
 'Исследование механизмов образования, способов и средств подавления контактных помех радиоприему'
 'Разработка моста переменного тока'
 'Разработка нательных антенн и излучателей для интернета вещей'
 'Разработка глоссария физических терминов для мультилингваперевода задач по физике различной сложности для иностранных слушателей подготовительных отделений'
 'Умные примерочные III. Проект интеллектуальной RFID системы'
 'Топологические приложения в магнитной гидродинамике'
 'Разработка микроволновой установки для процесса отверждения полимерных композиционных материалов в виде труб'
 'Cплайн-интерполяция и аппроксимация в SciPy'
 'Перспективная геофизическая информационно-измерительная система на основе новых способов передачи данных'
 'Аппаратно-программный комплекс калибровки с удалённым доступом средств измерения электрических величин'
 'Библиотека демонстрационно-образовательных программ в среде Матлаб для курса "Ан

In [14]:
#integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[311  92 211 213 191 300 297 207   1 147  29  37 318 134 256 205  47 257
 314  20 236 185  33  49  61 199  73 225 190 208  39 244  98 142 269 317
 196  35 193 123 224 187  45 215  97  84 169  87  48 231  60 203 227 107
 312 306 148 114 129 173 316 239 265  28 220 163 162  81 272  62 296 263
 253 293 178 204  82 132 282 281  91  79 277 109 110  10  21  89  51  24
 268  46 304   7 319 307   8 275 167 176  66  71 248  93 289 154   0  25
  22  76  74 141 310  65 137 292 283  94 146  70 113  57 118  32 111 195
 155 247 233 139   3 258   9 102 143  75  77 104 103 101 112  88  68 291
 295 219 251  53 128  86 234 144 138   6 182  26  72 170  83 299 298 160
 192 177 255 117 278 157 302 254 210 108 261 126  56  58  52 303 202 222
  30  27  54  64  85 229 194 159   5 270  90 172 171 249 294  15  42 264
  80 290 140 305 116 259 245 246 174 161 284 183 212  12  99 180 260 214
 105 106 166 267 184 201  17  19  44  43 131 156 262 168 175 186 218 223
 230 237 315 238 240 241 179 252 266 301 286 198 24

In [15]:
#binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [16]:
#invert encoding
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['Численное и аналитическое исследование эффекта Саффмана-Тейлора']
